/**
* @file encoder_main.cpp
 * @brief Command-line utility for compressing files using Huffman encoding.
 * * Supports standard flags (-i, -o, -h, -s) for input, output, help,
 * and compression statistics respectively.
 */
#include <iostream>
#include <string>
#include <unistd.h>
#include <filesystem>
#include "Huffman.h"

void printHelp() {
    std::cout << "Usage: ./encoder [options]" << std::endl;
    std::cout << "Options:" << std::endl;
    std::cout << "-h        : outputs this help message and exits the program" << std::endl;
    std::cout << "-i <file> : input file, the one you want to compress" << std::endl;
    std::cout << "-o <file> : output file, generated by the program" << std::endl;
    std::cout << "-s        : outputs detailed statistics about the compression" << std::endl;
}

int main(int argc, char *argv[]) {
    std::string inputFile = "";
    std::string outputFile = "";
    bool showStats = false;

    int option;
    //getopt passed through all the arguments
    //hi:o:s means that -h -i -o -s are accepted and i and o need a word after them
    while ((option = getopt(argc, argv, "hi:o:s")) != -1) {
        switch (option) {
            case 'h':
                printHelp();
                return 0;
            case 'i':
                inputFile = optarg;
                break;
            case 'o':
                outputFile = optarg;
                break;
            case 's':
                showStats = true;
                break;
            default:
                printHelp();
                return 1;
        }
    }
    if (inputFile == "") {
        std::cerr << "Error: No input file specified. Standard input (stdin) is not supported by this implementation of Huffman." << std::endl;
        return 1;
    }
    if (outputFile == "") {
        std::cerr << "Error: No output file specified (-o is required)." << std::endl;
        return 1;
    }
    if (!std::filesystem::exists(inputFile)) {
        std::cerr << "Error: input file" << inputFile << "does not exist\n";
        return 1;
    }

    Huffman huffman;
    huffman.compressFile(inputFile, outputFile);
    if (showStats) {
        //search on the hard disk how big the files are
        uintmax_t uncompressedSize = std::filesystem::file_size(inputFile);
        uintmax_t compressedSize = std::filesystem::file_size(outputFile);
        //casting in order to not lose the
        double spaceSaving = 100.0 * (1.0 - (static_cast<double>(compressedSize) /uncompressedSize));
        std::cout << "STATISTIC COMPRESSING\n" << std::endl;
        std::cout << "Original size (-i): " << uncompressedSize << "bytes\n";
        std::cout << "Compressed size (-o): " << compressedSize << "bytes\n";
        std::cout << "Space saving: " << spaceSaving << "%\n";
    }
    return 0;
}